# Generated by Django 5.1.2 on 2025-11-21 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='tx_user_created_idx',
            old_name='notes_trans_user_id_a0c9ab_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='tx_status_created_idx',
            old_name='notes_trans_status_63a839_idx',
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'status'], name='tx_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'updated_at'], name='tx_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tx_hash'], name='tx_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'status', '-created_at'], name='tx_user_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at', 'status'], name='tx_created_status_idx'),
        ),
    ]
