# Generated by Django 5.1.2 on 2025-12-01 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_rename_notes_trans_user_id_a0c9ab_idx_tx_user_created_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='signed_tx_cbor',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='unsigned_tx_cbor',
        ),
        migrations.AddField(
            model_name='note',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note', to='notes.transaction'),
        ),
    ]
